// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user_srv/internal/biz"
	"user_srv/internal/conf"
	"user_srv/internal/data"
	"user_srv/internal/server"
	"user_srv/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userSrvUsecase := biz.NewUserSrvUsecase(userRepo, logger)
	userService := service.NewUserService(userSrvUsecase)
	iNamingClient := data.NewClient(confData)
	nacosClient, cleanup2, err := data.NewNacosClient(confData, logger, iNamingClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, userService, logger, nacosClient)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
