// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"order_srv/internal/biz"
	"order_srv/internal/conf"
	"order_srv/internal/data"
	"order_srv/internal/server"
	"order_srv/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	iNamingClient := data.NewClient(confData)
	nacosClient, cleanup2, err := data.NewNacosClient(confData, logger, iNamingClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	goodsClient := data.NewGoodsSrvClient(confData, nacosClient)
	inventoryClient := data.NewInventorySrvClient(confData, nacosClient)
	orderListener, err := data.NewOrderListener(dataData, goodsClient, inventoryClient)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderRepo := data.NewOrderRepo(dataData, logger, goodsClient, inventoryClient, orderListener)
	orderUsecase := biz.NewOrderUsecase(orderRepo, logger)
	orderService := service.NewOrderService(orderUsecase)
	grpcServer := server.NewGRPCServer(confServer, orderService, logger, nacosClient)
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
