// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"goods_srv/internal/biz"
	"goods_srv/internal/conf"
	"goods_srv/internal/data"
	"goods_srv/internal/server"
	"goods_srv/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	brandsRepo := data.NewBrandsRepo(dataData, logger)
	brandsUsecase := biz.NewBrandsUsecase(brandsRepo, logger)
	bannerRepo := data.NewBannerRepo(dataData, logger)
	bannerUsecase := biz.NewBannerUsecase(bannerRepo, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	goodsCategoryBrandRepo := data.NewGoodsCategoryBrandRepoRepo(dataData, logger)
	goodsCategoryBrandUsecase := biz.NewGoodsCategoryBrandUsecase(goodsCategoryBrandRepo, logger)
	client, err := data.NewEsClient(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	esClient := data.NewESClient(client)
	goodsRepo := data.NewGoodsRepo(dataData, logger, esClient)
	goodsUsecase := biz.NewGoodsUsecase(goodsRepo, logger)
	goodsService := service.NewGoodsService(brandsUsecase, bannerUsecase, categoryUsecase, goodsCategoryBrandUsecase, goodsUsecase)
	iNamingClient := data.NewClient(confData)
	nacosClient, cleanup2, err := data.NewNacosClient(confData, logger, iNamingClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, goodsService, logger, nacosClient)
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
